package fr.formation.afpa.domain;
// Generated 6 avr. 2021 10:16:04 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch", catalog = "bd")
public class Branch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -660377808967999983L;
	private Integer branchId;
	private String address;
	private String city;
	private String name;
	private String state;
	private String zipCode;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Branch() {
	}

	public Branch(String name) {
		this.name = name;
	}

	public Branch(String address, String city, String name, String state, String zipCode,
			Set<Employee> employees) {
		this.address = address;
		this.city = city;
		this.name = name;
		this.state = state;
		this.zipCode = zipCode;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BRANCH_ID", unique = true, nullable = false)
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "ADDRESS", length = 30)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "STATE", length = 10)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_CODE", length = 12)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
